//Script GUID:d81bf5ef-72ed-4f67-a00e-bef3d3141e29
//Used for tracking history
//GDPR

[PIN] REFERENCE @"/shares/skypedata.adhoc/SkypeHelpers/Latest/SkypeHelpers.dll";
[PIN] REFERENCE @"/shares/skypedata.adhoc/SkypeSchemas/Latest/SkypeSchemas.dll";


MODULE "/shares/PXSCosmos14.Prod/PXS.DeleteSignal.PROD/PrivacyAnnotation/PrivacyAnnotation.module";
USING Privacy;

//=========================================================Output===========================================================================

#DECLARE Semantic_Basedata  string   = @"/shares/skypedata.adhoc/local/microsoftteams/data/DataScience/ProdIntelligence/Copilot/SemanticStream/IdeasValidation.ss";

Semantic_Base =
    SELECT TenantId,
           UserId,
           EngagementLevel,
           SubworkloadScenario
    FROM
    (
        VIEW @"/shares/skypedata.adhoc/local/microsoftteams/data/prod/SemanticStreams/structured/SemanticStreamInternal.view"
        PARAMS
        (
            startDate = DateTime.Parse(@"2023-05-01"),
            endDate = DateTime.Parse(@"2023-05-23"),
            Modality = "copilot"
        )
    )
    GROUP BY TenantId,
             UserId,
             EngagementLevel,
             SubworkloadScenario;

Semantic =
    SELECT COUNT(DISTINCT (UserId)) AS UserCount,
           COUNT(DISTINCT (TenantId)) AS TenantCount
    FROM Semantic_Base
    WHERE EngagementLevel IN("Engaged", "Active") AND SubworkloadScenario NOT IN ("See chat Copilot smart action", "See Copilot bot smart action");
                  



/*
[Privacy.DataType.ProductAndServiceUsage]
[Privacy.Column.TenantId(Column="TenantId")]
[Privacy.Column.TenantId(Column="UserId")]
OUTPUT
TO SSTREAM @Semantic_Basedata
WITH STREAMEXPIRY "90";
*/
[Privacy.Asset.NonPersonal]
OUTPUT
TO SSTREAM @Semantic_Basedata
   WITH STREAMEXPIRY "10";